### ISSUE TITLE
Events list sizing problem

### ISSUE THREAD

**Issue by dhowe** [dhowe/Website#242]
More button disappears below footer

**Comment by cqx931** [comment]
Please check the latest fix for this: https://github.com/dhowe/Website/commit/cb73a46adb753543af3de6e134655e5bf462013a

**Comment by cqx931** [comment]
fixed #243, so close now

**Comment by dhowe** [comment]
still seeing problems with this (here the list is not long enough):

![image](https://user-images.githubusercontent.com/737638/88946580-01912800-d2c2-11ea-8b33-70a827332042.png)

**Comment by dhowe** [comment]
I think the problem is that it is counting the space for the footer, whether or not it is showing...

**Comment by dhowe** [comment]
Just saw this again
